
development:
  adapter: postgresql
  encoding: unicode
  database: car_dealership_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: car_dealership_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: car_dealership_production
  pool: 5
  username:
  password:
